### ISSUE TITLE
Pods are healthy, but operator says: minimum replication size is not met, only 0 are healthy

### ISSUE THREAD

**Issue by sim1** [amaizfinance/redis-operator#29] opened 2021-02-27 18:44 UTC
Kubernetes 1.20.4
Redis-operator manifests:
```
kustomize build github.com/sim1/katalog/redis-operator/default?ref=0.0.4
```
(upstream kustomize remote + 0.2.0 -> latest image tag rewrite due to #24)

Manifest:
```
---
apiVersion: k8s.amaiz.com/v1alpha1
kind: Redis
metadata:
  # the .metadata.labels will be added to all generated resources along with the
  # redis=example label
  labels:
    component: redis
  # the name of the Redis resource will be used as a label for all generated resources,
  # and as the infix or suffix for them.
  name: super
spec:
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - redis
            topologyKey: kubernetes.io/hostname
          weight: 70
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default

  dataVolumeClaimTemplate:
    metadata:
      name: redis-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  # Redis container definition (required)
  # image, resources and securityContext are the same as found in v1.Container.
  # More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core
  redis:
    image: redis:alpine
    initialDelaySeconds: 10
    resources:
      requests:
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      readOnlyRootFilesystem: true
      runAsUser: 7777777
      runAsGroup: 7777777
      fsGroup: 7777777
      runAsNonRoot: true
```

Logs:
```
~ » k get svc,ep,pod
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/redis-super            ClusterIP   10.35.154.189   <none>        6379/TCP   118s
service/redis-super-headless   ClusterIP   None            <none>        6379/TCP   118s
service/redis-super-master     ClusterIP   10.44.178.120   <none>        6379/TCP   118s

NAME                             ENDPOINTS                                                    AGE
endpoints/redis-super            100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   118s
endpoints/redis-super-headless   100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   118s
endpoints/redis-super-master     <none>                                                       118s

NAME                         READY   STATUS                       RESTARTS   AGE
pod/redis-super-0            1/1     Running                      0          118s
pod/redis-super-1            1/1     Running                      0          82s
pod/redis-super-2            1/1     Running                      0          45s
pod/super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          118s
~ » k get svc,ep,pod
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/redis-super            ClusterIP   10.35.154.189   <none>        6379/TCP   119s
service/redis-super-headless   ClusterIP   None            <none>        6379/TCP   119s
service/redis-super-master     ClusterIP   10.44.178.120   <none>        6379/TCP   119s

NAME                             ENDPOINTS                                                    AGE
endpoints/redis-super            100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   119s
endpoints/redis-super-headless   100.64.187.97:6379,100.65.142.252:6379,100.65.142.253:6379   119s
endpoints/redis-super-master     <none>                                                       119s

NAME                         READY   STATUS                       RESTARTS   AGE
pod/redis-super-0            1/1     Running                      0          119s
pod/redis-super-1            1/1     Running                      0          83s
pod/redis-super-2            1/1     Running                      0          46s
pod/super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          119s
~ » kns redis-operator
stern Set context namespace to "redis-operator"
.
~ » stern .
+ redis-operator-6bd5b89477-74lp9 › redis-operator
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.120Z","logger":"cmd","msg":"Redis-Operator Version: latest"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.120Z","logger":"cmd","msg":"Go Version: go1.15.1"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"cmd","msg":"Version of operator-sdk: v0.17.1"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:54.121Z","logger":"leader","msg":"Trying to become the leader."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:56.728Z","logger":"leader","msg":"No pre-existing lock was found."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:56.773Z","logger":"leader","msg":"Became the leader."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:59.309Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:26:59.310Z","logger":"cmd","msg":"Registering Components."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.590Z","logger":"metrics","msg":"Metrics Service object created","Service.Name":"redis-operator-metrics","Service.Namespace":"redis-operator"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.590Z","logger":"cmd","msg":"Starting the Cmd."}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.591Z","logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.591Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.692Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:04.995Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.095Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.196Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.298Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.401Z","logger":"controller-runtime.controller","msg":"Starting Controller","controller":"redis-controller"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:27:05.401Z","logger":"controller-runtime.controller","msg":"Starting workers","controller":"redis-controller","worker count":1}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.265Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.307Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.349Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.442Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.485Z","logger":"controller_redis","msg":"Applied *v1.ConfigMap","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.519Z","logger":"controller_redis","msg":"Applied *v1beta1.PodDisruptionBudget","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.651Z","logger":"controller_redis","msg":"Applied *v1.StatefulSet","Namespace":"super","Redis":"super"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.856Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.859Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.972Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:50.999Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.001Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.029Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:51.030Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:37:53.534Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:38:31.895Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:38:36.898Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:12.902Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:22.904Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:32.907Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:39:50.139Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}


redis-operator-6bd5b89477-74lp9 redis-operator {"level":"info","ts":"2021-02-27T18:40:05.142Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"super","Redis":"super","error":"minimum replication size is not met, only 0 are healthy"}
^C
~ » k get pod -n super
NAME                     READY   STATUS                       RESTARTS   AGE
redis-super-0            1/1     Running                      0          2m48s
redis-super-1            1/1     Running                      0          2m12s
redis-super-2            1/1     Running                      0          95s
super-774fd5458f-pvzn7   0/2     CreateContainerConfigError   0          2m48s
~ »
```

**Comment by schlitzered** [comment] 2021-03-03 16:56
i just tied myself with image: amaiz/redis-operator:latest, and i am getting the same issue on an kubernetes 1.19.6 cluster.

**Comment by nrvnrvn** [comment] 2021-03-31 06:01
@schlitzered @sim1 could you please check if the issue is fixed with the release v0.2.1?

**Comment by Escaflow** [comment] 2021-07-08 07:50
We are hiting the same issue, all 3 pods are up and healthy but no master gets elected. We are running k8 v1.19.9
Interesting enough the first deployment worked, just after the next one we run into this issue.


srv/pod/ep
```
service/redis-foo                  ClusterIP   10.233.37.249   <none>        6379/TCP,9121/TCP   10m
service/redis-foo-headless         ClusterIP   None            <none>        6379/TCP,9121/TCP   10m
service/redis-foo-master           ClusterIP   10.233.62.160   <none>        6379/TCP,9121/TCP   10m
endpoints/redis-foo                  10.233.64.93:6379,10.233.64.94:6379,10.233.65.220:6379 + 3 more...   10m
endpoints/redis-foo-headless         10.233.64.93:6379,10.233.64.94:6379,10.233.65.220:6379 + 3 more...   10m
endpoints/redis-foo-master           <none>                                                               10m
pod/redis-foo-0                            2/2     Running   0          10m
pod/redis-foo-1                            2/2     Running   0          10m
pod/redis-foo-2                            2/2     Running   0          10m
```

Operator Logs:
```
{"level":"info","ts":"2021-07-08T07:07:05.101Z","logger":"cmd","msg":"Redis-Operator Version: v0.2.1"}
{"level":"info","ts":"2021-07-08T07:07:05.101Z","logger":"cmd","msg":"Go Version: go1.16.2"}
{"level":"info","ts":"2021-07-08T07:07:05.101Z","logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2021-07-08T07:07:05.101Z","logger":"cmd","msg":"Version of operator-sdk: v0.18.2"}
{"level":"info","ts":"2021-07-08T07:07:05.102Z","logger":"leader","msg":"Trying to become the leader."}
I0708 07:07:06.153110       1 request.go:621] Throttling request took 1.038100721s, request: GET:https://10.233.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
{"level":"info","ts":"2021-07-08T07:07:07.133Z","logger":"leader","msg":"Found existing lock","LockOwner":"redis-operator-d4557966c-fsl6q"}
{"level":"info","ts":"2021-07-08T07:07:07.144Z","logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":"2021-07-08T07:07:08.278Z","logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":"2021-07-08T07:07:10.666Z","logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":"2021-07-08T07:07:15.205Z","logger":"leader","msg":"Became the leader."}
I0708 07:07:16.256457       1 request.go:621] Throttling request took 1.045216589s, request: GET:https://10.233.0.1:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":"2021-07-08T07:07:17.214Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":"2021-07-08T07:07:17.215Z","logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":"2021-07-08T07:07:21.268Z","logger":"metrics","msg":"Metrics Service object updated","Service.Name":"redis-operator-metrics","Service.Namespace":"redis-operator"}
{"level":"info","ts":"2021-07-08T07:07:23.275Z","logger":"cmd","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com \"redis-operator-metrics\" already exists"}
{"level":"info","ts":"2021-07-08T07:07:23.275Z","logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":"2021-07-08T07:07:23.276Z","logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":"2021-07-08T07:07:23.276Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:23.377Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:23.678Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:23.780Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:23.881Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:23.983Z","logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"redis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-07-08T07:07:24.084Z","logger":"controller-runtime.controller","msg":"Starting Controller","controller":"redis-controller"}
{"level":"info","ts":"2021-07-08T07:07:24.084Z","logger":"controller-runtime.controller","msg":"Starting workers","controller":"redis-controller","worker count":1}
{"level":"info","ts":"2021-07-08T07:31:32.192Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.205Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.217Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.237Z","logger":"controller_redis","msg":"Applied *v1.Service","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.242Z","logger":"controller_redis","msg":"Applied *v1.Secret","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.247Z","logger":"controller_redis","msg":"Applied *v1.ConfigMap","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.251Z","logger":"controller_redis","msg":"Applied *v1beta1.PodDisruptionBudget","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.381Z","logger":"controller_redis","msg":"Applied *v1.StatefulSet","Namespace":"foo","Redis":"foo"}
{"level":"info","ts":"2021-07-08T07:31:32.519Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:32.648Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:33.155Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:38.414Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:48.803Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:54.820Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:31:54.933Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:32:09.408Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:32:10.909Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:32:11.001Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:32:26.810Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:32:26.897Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}
{"level":"info","ts":"2021-07-08T07:34:53.349Z","logger":"controller_redis","msg":"Error creating Redis replication, requeue","Namespace":"foo","Redis":"foo","error":"minimum replication size is not met, only 0 are healthy"}

```

**Comment by Escaflow** [comment] 2021-07-08 09:54
Sorry for the posts, we found the issue.
We create the secrets with rng, and had an /n at the end of it so the authentication form operator -> redis-instance failed.
May i propose to handle this in the operaor logs (eg. the acual error from redis-cli: "Node 10.233.64.122:6379 replied with error: WRONGPASS invalid username-password pair or user is disabled.”)?

**Comment by nrvnrvn** [comment] 2022-06-15 09:50
closed in favor of https://github.com/nrvnrvn/redis-operator/issues/1

**Closed by nrvnrvn** 2022-06-15 09:50 UTC
